player-bar:
  type: SCOREBOARD # healthbar type (AKA location, can be SCOREBOARD or ACTION)
  style: ABSOLUTE # style of healthbar (ABSOLUTE, PERCENT, or BAR)
  useMainScoreboard: false # use the main scoreboard (true) or a new scoreboard (false)

mob-bar:
  type: NAME # healthbar type (AKA location, can be NAME or ACTION)
  style: BAR # style of healthbar (ABSOLUTE, PERCENT, or BAR)
  length: 20 # length of the bar (number of characters)
  char: 0x25ae # character to use for the bar
  showMobNames: true # if the mob's name should show alongside the healthbar (for NAME or ACTION type)
