name: SimpleHealthbars2
main: org.simplemc.simplehealthbars2.SimpleHealthbars2
version: "${version}"
api-version: "${apiVersion}"
website: https://github.com/SimpleMC/SimpleHealthbars2
author: tajobe
libraries:
  - org.jetbrains.kotlin:kotlin-stdlib-jdk8:${kotlinVersion}
