name: Release
on:
  push:
    tags:
      - 'release-*'

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Gradle Build
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: build
      - name: Release
        uses: docker://antonyurchenko/git-release:latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DRAFT_RELEASE: "true"
        with:
          args: build/libs/simplehealthbars2-*-all.jar
